TypeAdapter generator
eclipse-ecal/rosidl_typesupport_protobuf pull request #27
Opened 2023-12-08 01:45 UTC by gonzodepedro

Adds automatic rclcpp::TypeAdapter generation for protobuf.

**Note:** Code is ready for review, documentation will come later.
**Note:** To be merged after #26

2023-12-11 12:31 UTC, FlorianReimold requested changes

2023-12-11 12:31 UTC, FlorianReimold commented on rosidl_typesupport_protobuf_cpp/resource/idl__typeadapter_protobuf_cpp.hpp.em
> +<<<<<<< HEAD
A wild merge conflict appears 🐛

2023-12-11 18:16 UTC, gonzodepedro commented on rosidl_typesupport_protobuf_cpp/resource/idl__typeadapter_protobuf_cpp.hpp.em
> +<<<<<<< HEAD
Fixed

2023-12-12 16:39 UTC, FlorianReimold commented
Hm, GitHub now prompts me to resolve some merge conflicts between your fork and the master branch

2023-12-13 07:13 UTC, tfoote commented
I rebased the changes onto the recent PRs. It's passing CI now. 

The copyright tests were failing due to being overly strict. I've ticketed to restore them at https://github.com/tfoote/rosidl_typesupport_protobuf/issues/11

2023-12-13 21:36 UTC, gonzodepedro commented
**Attention: this branch has changed and been force pushed**

2023-12-15 11:00 UTC, FlorianReimold commented
I am currently checking back with Eclipse if there are any processes to follow, as this contribution is very big and reviewing it line by line is probably not the best approach here.

2023-12-18 17:48 UTC, gonzodepedro commented
We will try to split this into multiple shorter and hopefully easier to review PRs.

2023-12-21 18:25 UTC, gonzodepedro commented
We have split this PR into 3 more manageable PRs.
Closing this, in favor of #30, #31 and #32

2023-12-21 18:25 UTC, closed without merging